# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
      - "**-devmaj"
      - "**-relcert"
      - "**-prd"
    types: [closed]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          TEST_ARR: ${{secrets['KEY']}}
      run: |
        echo The PR number is $PR_NUMBER
        echo Branch name: $BRANCH_NAME
        echo Ref: ${GITHUB_REF##*/}
        echo Key=${{secrets['KEY']}}

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
